### ISSUE TITLE
KeyError 'name' ('repository.owner.name')

### ISSUE THREAD

**Issue by steinnes** [NiklasRosenstein/flux#25]
I'm having an issue where I get a 500 error on push events, the problem is that the payload does not include a `name` parameter for the `owner` of the repository in question.  See the screenshot here for the payload data:

![image](https://cloud.githubusercontent.com/assets/1097582/15877168/9dd658e0-2d01-11e6-8428-b40fb36267a2.png)

I have forked the repository and I am doing some work there to see if I can use this at work to replace our external CI system, I'll make a patch there to rely on `repository.owner.login` if name can not be found.

Why `name` is missing for me is unclear, the account in question is mine and I have my full name set.

**Comment by NiklasRosenstein** [comment]
Hm I think this is indeed an error and it should use `repository.owner.login` instead of `repository.owner.name`. Would you try it and submit a patch? Thanks!

**Comment by steinnes** [comment]
This is due to me sending non-push events to the system.  Maybe we should add to the README.md that when setting up the GitHub webhook you should only enable *push* events.  Since I did not know which events were supported I opted for *all* :-)

See here a screenshot of actual push payload:
![image](https://cloud.githubusercontent.com/assets/1097582/15938560/3530ad82-2e63-11e6-998b-eb7d77d54f0c.png)

**Comment by NiklasRosenstein** [comment]
Yeah, sorry for the lack of this information! At least now, Flux will respond with

    Payload rejected (expected 'push' event, got 'event-type')

[If any event but a push event is received from GitHub.](https://github.com/NiklasRosenstein/flux/blob/81c5971ae575c10f4852cd00b03c326e4aaf127b/flux/views.py#L70-L73)

I kind of thought it was obvious since the URL on the Flux side is `/hook/push`. I'll add it to the README.md ;)

**Comment by NiklasRosenstein** [comment]
What other event would make sense to trigger a build other than PUSH?

**Comment by steinnes** [comment]
The only case where I would need a build but a push was not the source of it, would be when I merge a pull request to master (or another branch), thus creating a new commit on GitHub without pushing.  Maybe that actually sends a push event? :-)

**Comment by NiklasRosenstein** [comment]
I'm not 100% sure, but my guts tell me that it would trigger a push event.
:D
