### ISSUE TITLE
development halted?

### ISSUE THREAD

**Issue by gsantner** [NiklasRosenstein/flux#32]
HI there,

 just found this project by looking for a lightweight ci/cd with gogs/gitea support. I found quite some open tasks (that you seem to wanted to do) but no work on it for quite some time. Hence the question - is this project dead/halted or are you fine with the current abilities?

**Comment by NiklasRosenstein** [comment]
Hi! Enhancing this project is not up high on my priority list, although I would love to see it grow. You are most welcome if you want to contribute, of course. I am not actually using it myself at the moment. While I think it works reasonably well in its current state, I would not recommend production use.

On a side-note, I recently thought about this project and was thinking about adding support (or changing it completely to *only* work with) Docker containers.

**Comment by gsantner** [comment]
can you though recommend something tiny and small that would run on a rpi? i basically dont need more than running bash commands :D (sidenote: gitea server has no connection to target, so git hooks is not the thing)

**Comment by NiklasRosenstein** [comment]
Well, for a small instance on a Raspberry Pi, it might actually suffice. 😉 
I don't know much about other open source CI services except for the one in GitLab (definitely not lightweight) and Jenkins (not lightweight either).

**Comment by gsantner** [comment]
did I understood it right, that there need to be a shell script ij repo root and this will be run after scm pull?

**Comment by NiklasRosenstein** [comment]
Yes, exactly. All flux does is pull your repository, and then it runs the `.flux-build.sh` file in your repository. Note that this is not in any way armored or containerized, so the script has all the access that the flux user has (which can be a good thing, but also a bad thing).

**Comment by gsantner** [comment]
and the exit code is used as build status right? with 0 as OK?

container: no problem, I am the only pushing member

**Comment by NiklasRosenstein** [comment]
> and the exit code is used as build status right? with 0 as OK?

Yep!
